import { useEffect, useMemo, useState } from 'react';
import * as alertService from '../../services/alertService';
import AlertTable from '../../components/AlertTable';
import LoadingState from '../../components/LoadingState';
import ErrorState from '../../components/ErrorState';

const TABS = ['All', 'Critical', 'High', 'Medium', 'Low', 'Resolved'];

export default function Alerts() {
  const [alerts, setAlerts] = useState([]);
  const [status, setStatus] = useState('loading');
  const [tab, setTab] = useState('All');

  function load() {
    setStatus('loading');
    alertService.getAlerts()
      .then((data) => { setAlerts(data); setStatus('ready'); })
      .catch(() => setStatus('error'));
  }

  useEffect(load, []);

  const filtered = useMemo(() => {
    if (tab === 'All') return alerts;
    if (tab === 'Resolved') return alerts.filter((a) => a.status === 'Resolved' || a.status === 'False Positive');
    return alerts.filter((a) => a.severity === tab);
  }, [alerts, tab]);

  const counts = useMemo(() => {
    const c = { All: alerts.length, Resolved: 0, Critical: 0, High: 0, Medium: 0, Low: 0 };
    alerts.forEach((a) => {
      c[a.severity] = (c[a.severity] || 0) + 1;
      if (a.status === 'Resolved' || a.status === 'False Positive') c.Resolved += 1;
    });
    return c;
  }, [alerts]);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-ink-900">Security Alerts</h1>
        <p className="text-sm text-ink-500 mt-1">Review and triage alerts generated by the detection rules engine.</p>
      </div>

      <div className="flex flex-wrap gap-2 border-b border-ink-100 pb-3">
        {TABS.map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`px-3.5 py-1.5 rounded-full text-sm font-medium transition-colors ${
              tab === t ? 'bg-brand-600 text-white' : 'bg-ink-100 text-ink-600 hover:bg-ink-200'
            }`}
          >
            {t} <span className="opacity-70">({counts[t] ?? 0})</span>
          </button>
        ))}
      </div>

      <div className="card p-0 overflow-hidden">
        {status === 'loading' && <LoadingState label="Loading alerts..." />}
        {status === 'error' && <ErrorState onRetry={load} />}
        {status === 'ready' && <AlertTable alerts={filtered} />}
      </div>
    </div>
  );
}
